import type { DiagnosticScenario } from './types';

export const diagnosticScenarios: DiagnosticScenario[] = [
  {
    id: 'lg-cj87-boot-failure',
    name: 'LG CJ87 Boot Failure',
    boardName: 'LG CJ87 Main Board',
    description: 'Standby and core rails are present, but the main board does not release boot commands.',
    measurements: [
      {
        id: 'standby_5v',
        label: '5.1VA standby',
        kind: 'voltage',
        status: 'present',
        value: 5.1,
        unit: 'V',
        lineId: 'standby_5v',
      },
      {
        id: 'rail_14v',
        label: '14VA',
        kind: 'voltage',
        status: 'present',
        value: 14.2,
        unit: 'V',
        lineId: 'rail_14v',
      },
      {
        id: 'rail_12v_initial',
        label: '12V rail initial',
        kind: 'voltage',
        status: 'absent',
        value: 0,
        unit: 'V',
        lineId: 'rail_12v',
      },
      {
        id: 'rail_12v_forced',
        label: '12V rail after PFC_PCTL forced',
        kind: 'voltage',
        status: 'forced-active',
        value: 12.1,
        unit: 'V',
        lineId: 'rail_12v',
        note: 'PFC_PCTL forced externally',
      },
      {
        id: 'rail_3v3',
        label: '3.3V logic rail',
        kind: 'voltage',
        status: 'present',
        value: 3.31,
        unit: 'V',
        lineId: 'rail_3v3',
      },
      {
        id: 'rail_1v2',
        label: '1.2V core rail',
        kind: 'voltage',
        status: 'present',
        value: 1.19,
        unit: 'V',
        lineId: 'rail_1v2',
      },
      {
        id: 'spi_vcc',
        label: 'SPI VCC',
        kind: 'voltage',
        status: 'present',
        value: 3.29,
        unit: 'V',
        lineId: 'spi_flash',
      },
      {
        id: 'cpu_temperature',
        label: 'CPU thermal response',
        kind: 'temperature',
        status: 'cold',
        value: 28,
        unit: 'C',
        lineId: 'cpu_core',
      },
      {
        id: 'pfc_pctl',
        label: 'PFC_PCTL command',
        kind: 'logic',
        status: 'absent',
        value: 0,
        unit: 'V',
        lineId: 'pfc_pctl',
      },
      {
        id: 'l304_activity',
        label: 'L304 switching activity',
        kind: 'status',
        status: 'dead',
        lineId: 'l304',
      },
      {
        id: 'l304_resistance',
        label: 'L304 output resistance',
        kind: 'resistance',
        status: 'ok',
        value: 8.7,
        unit: 'ohm',
        lineId: 'l304',
        note: 'No hard short detected',
      },
      {
        id: 'board_current',
        label: 'Board current draw',
        kind: 'current',
        status: 'ok',
        value: 0.42,
        unit: 'A',
        lineId: 'main_input',
      },
    ],
    boardLines: [
      { id: 'standby_5v', name: '5.1VA Standby', role: 'standby', topology: 'rail', nominalVoltage: 5 },
      { id: 'rail_14v', name: '14VA Input', role: 'primary', topology: 'rail', nominalVoltage: 14 },
      { id: 'rail_12v', name: '12V Secondary', role: 'secondary', topology: 'rail', nominalVoltage: 12 },
      { id: 'rail_3v3', name: '3.3V Logic', role: 'logic', topology: 'rail', nominalVoltage: 3.3 },
      { id: 'rail_1v2', name: '1.2V Core', role: 'logic', topology: 'rail', nominalVoltage: 1.2 },
      { id: 'spi_flash', name: 'SPI Flash', role: 'data', topology: 'spi', nominalVoltage: 3.3 },
      { id: 'cpu_core', name: 'CPU Core', role: 'load', topology: 'cpu' },
      { id: 'pfc_pctl', name: 'PFC_PCTL', role: 'control', topology: 'control' },
      {
        id: 'l304',
        name: 'L304 Secondary Rail',
        role: 'secondary',
        topology: 'inductor',
        outputMeasurementId: 'l304_activity',
        resistanceMeasurementId: 'l304_resistance',
      },
    ],
  },
  {
    id: 'buck-converter-failure',
    name: 'Buck Converter Failure',
    boardName: 'Generic DC/DC Section',
    description: 'Input and enable are present, but the buck converter output remains absent without a short.',
    measurements: [
      {
        id: 'buck_vin',
        label: 'Buck VIN',
        kind: 'voltage',
        status: 'present',
        value: 19.1,
        unit: 'V',
        lineId: 'buck_converter',
      },
      {
        id: 'buck_enable',
        label: 'Buck ENABLE',
        kind: 'logic',
        status: 'present',
        value: 3.28,
        unit: 'V',
        lineId: 'buck_converter',
      },
      {
        id: 'buck_vout',
        label: 'Buck VOUT',
        kind: 'voltage',
        status: 'absent',
        value: 0.02,
        unit: 'V',
        lineId: 'buck_converter',
      },
      {
        id: 'buck_resistance',
        label: 'Buck output resistance',
        kind: 'resistance',
        status: 'ok',
        value: 11.8,
        unit: 'ohm',
        lineId: 'buck_converter',
      },
      {
        id: 'buck_current',
        label: 'Buck input current',
        kind: 'current',
        status: 'ok',
        value: 0.19,
        unit: 'A',
        lineId: 'buck_converter',
      },
    ],
    boardLines: [
      {
        id: 'buck_converter',
        name: 'Buck Converter',
        role: 'secondary',
        topology: 'buck',
        nominalVoltage: 5,
        inputMeasurementId: 'buck_vin',
        enableMeasurementId: 'buck_enable',
        outputMeasurementId: 'buck_vout',
        resistanceMeasurementId: 'buck_resistance',
        currentMeasurementId: 'buck_current',
      },
    ],
  },
  {
    id: 'shorted-rail',
    name: 'Shorted Rail',
    boardName: 'Low Resistance Rail',
    description: 'The target line shows very low resistance, excessive current and a collapsing voltage rail.',
    measurements: [
      {
        id: 'short_voltage',
        label: 'Target rail voltage',
        kind: 'voltage',
        status: 'low',
        value: 0.18,
        unit: 'V',
        lineId: 'shorted_line',
      },
      {
        id: 'short_current',
        label: 'Injected current',
        kind: 'current',
        status: 'high',
        value: 2.6,
        unit: 'A',
        lineId: 'shorted_line',
      },
      {
        id: 'short_resistance',
        label: 'Rail resistance',
        kind: 'resistance',
        status: 'low',
        value: 0.6,
        unit: 'ohm',
        lineId: 'shorted_line',
      },
    ],
    boardLines: [
      {
        id: 'shorted_line',
        name: 'Collapsed Rail',
        role: 'secondary',
        topology: 'rail',
        nominalVoltage: 3.3,
        voltageMeasurementId: 'short_voltage',
        currentMeasurementId: 'short_current',
        resistanceMeasurementId: 'short_resistance',
      },
    ],
  },
  {
    id: 'ldo-failure',
    name: 'LDO Failure',
    boardName: 'Linear Regulator Section',
    description: 'LDO input and enable are present, but regulated output is missing.',
    measurements: [
      {
        id: 'ldo_input',
        label: 'LDO input',
        kind: 'voltage',
        status: 'present',
        value: 5.04,
        unit: 'V',
        lineId: 'ldo_regulator',
      },
      {
        id: 'ldo_enable',
        label: 'LDO enable',
        kind: 'logic',
        status: 'present',
        value: 3.3,
        unit: 'V',
        lineId: 'ldo_regulator',
      },
      {
        id: 'ldo_output',
        label: 'LDO output',
        kind: 'voltage',
        status: 'absent',
        value: 0,
        unit: 'V',
        lineId: 'ldo_regulator',
      },
      {
        id: 'ldo_resistance',
        label: 'LDO output resistance',
        kind: 'resistance',
        status: 'ok',
        value: 24,
        unit: 'ohm',
        lineId: 'ldo_regulator',
      },
      {
        id: 'ldo_current',
        label: 'LDO input current',
        kind: 'current',
        status: 'ok',
        value: 0.08,
        unit: 'A',
        lineId: 'ldo_regulator',
      },
    ],
    boardLines: [
      {
        id: 'ldo_regulator',
        name: 'LDO Regulator',
        role: 'secondary',
        topology: 'ldo',
        nominalVoltage: 3.3,
        inputMeasurementId: 'ldo_input',
        enableMeasurementId: 'ldo_enable',
        outputMeasurementId: 'ldo_output',
        resistanceMeasurementId: 'ldo_resistance',
        currentMeasurementId: 'ldo_current',
      },
    ],
  },
];

export const defaultScenarioId = 'lg-cj87-boot-failure';
