import { motion } from 'framer-motion';
import { SquareTerminal } from 'lucide-react';
import type { EngineLog } from '../engine/types';

const levelClass = {
  SCAN: 'text-ion',
  TEST: 'text-pulse',
  WARN: 'text-warning',
  AI: 'text-plasma',
  FAIL: 'text-rose-300',
  INFO: 'text-slate-300',
};

type LogsPanelProps = {
  logs: EngineLog[];
};

// LogsPanel module: terminal-style event stream generated by the behavior engine.
export function LogsPanel({ logs }: LogsPanelProps) {
  return (
    <motion.section
      className="panel-glass terminal-panel p-4"
      initial={{ opacity: 0, y: 22 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.65, ease: 'easeOut', delay: 0.28 }}
    >
      <div className="mb-4 flex items-center justify-between gap-3">
        <div>
          <p className="eyebrow">Trace Output</p>
          <h2 className="panel-title">Live Logs</h2>
        </div>
        <div className="icon-shell">
          <SquareTerminal className="h-5 w-5 text-ion" aria-hidden="true" />
        </div>
      </div>

      <div className="space-y-2 font-mono text-sm">
        {logs.map((log, index) => (
          <motion.div
            className="log-line"
            key={`${log.level}-${log.message}-${index}`}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.35, delay: 0.4 + index * 0.08 }}
          >
            <span className={levelClass[log.level]}>[{log.level}]</span>
            <span className="text-slate-300">{log.message}</span>
          </motion.div>
        ))}
      </div>
    </motion.section>
  );
}
